# Generated by Django 5.2.6 on 2025-09-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionConceptoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('es_debito', models.BooleanField(default=False, help_text='Si es descuento = True, si es ingreso = False')),
                ('afecta_ips', models.BooleanField(default=True, help_text='Incluye o no en el cálculo del IPS (9%)')),
                ('para_aguinaldo', models.BooleanField(default=True, help_text='Incluye o no en el cálculo del aguinaldo')),
                ('recurrente', models.BooleanField(default=True, help_text='Si se aplica todos los meses o solo una vez')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificacion_hijos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ips_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ips_empleador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_debito', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente_desde', models.DateField(help_text='Fecha de inicio de vigencia')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
    ]
