# Generated by Django 5.2.6 on 2025-10-02 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_activo_empleado_direccion_empleado_email_and_more'),
        ('nomina_cal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='nominadetalle',
            name='nomina',
        ),
        migrations.RemoveField(
            model_name='nominadetalle',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='nominadetalle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nominadetalle',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='recurrente',
        ),
        migrations.RemoveField(
            model_name='salariominimo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salariominimo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salariominimo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salariominimo',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='concepto',
            name='es_recurrente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='afecta_ips',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='es_debito',
            field=models.BooleanField(default=False, help_text='True = descuento, False = ingreso'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='para_aguinaldo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salariominimo',
            name='vigente_desde',
            field=models.DateField(help_text='Fecha desde la cual rige este salario mínimo'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_cobrar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empleados.empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('empleado', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina_cal.concepto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina_cal.liquidacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AsignacionConceptoEmpleado',
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
        migrations.DeleteModel(
            name='NominaDetalle',
        ),
        migrations.DeleteModel(
            name='Retencion',
        ),
    ]
