# Generated by Django 5.2.6 on 2025-10-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_cal', '0003_remove_nomina_created_by_remove_nomina_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidacion',
            old_name='cerrado',
            new_name='cerrada',
        ),
    ]
