# Generated by Django 5.2.6 on 2025-10-06 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_activo_empleado_direccion_empleado_email_and_more'),
        ('nomina_cal', '0005_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.RenameField(
            model_name='descuento',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salariominimo',
            name='vigente',
            field=models.BooleanField(default=True, help_text='Marca si es el salario actual vigente'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado al que se aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='recurrente',
            field=models.BooleanField(default=False, help_text='Se aplica automáticamente cada mes'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.CharField(choices=[('prestamo', 'Préstamo'), ('embargo', 'Embargo Judicial'), ('ausencia', 'Ausencia'), ('retencion', 'Retención Sindical'), ('otro', 'Otro Descuento')], default='otro', max_length=50),
        ),
    ]
