# Generated by Django 5.2.6 on 2025-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_cal', '0006_alter_descuento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='enviado_email',
            field=models.BooleanField(default=False, help_text='Indica si el recibo ya fue enviado por correo'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
