# Generated by Django 5.2.6 on 2025-10-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_empleado_options_alter_hijo_options_and_more'),
        ('nomina_cal', '0007_liquidacion_enviado_email_liquidacion_fecha_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'Liquidación', 'verbose_name_plural': 'Liquidaciones'},
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('destinatario', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('enviado', 'enviado'), ('error', 'error')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_correo', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
