# Generated by Django 5.2.6 on 2025-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_activo_empleado_direccion_empleado_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hijo',
            old_name='reside_py',
            new_name='residente',
        ),
        migrations.AddField(
            model_name='hijo',
            name='fecha_vencimiento_residencia',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del comprobante de residencia', null=True),
        ),
        migrations.AddField(
            model_name='hijo',
            name='vida_residencia',
            field=models.FileField(blank=True, help_text='Comprobante de vida y residencia', null=True, upload_to='residencias/'),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='certificado_nacimiento',
            field=models.FileField(blank=True, help_text='Archivo escaneado del certificado de nacimiento', null=True, upload_to='certificados/'),
        ),
    ]
