# Generated by Django 5.2.6 on 2025-10-24 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_rename_reside_py_hijo_residente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCargoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
