# Generated by Django 5.2.6 on 2025-10-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_empleado_estado_civil_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administración'), ('RRHH', 'Recursos Humanos'), ('IT', 'Tecnología'), ('VENTAS', 'Ventas'), ('OTROS', 'Otros')], default='OTROS', help_text='Departamento o área donde trabaja el empleado.', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo fijo'), ('TEMPORAL', 'Temporal')], default='INDEFINIDO', help_text='Tipo de contrato laboral (indefinido, temporal, etc.).', max_length=20),
        ),
    ]
