# Generated by Django 5.2.6 on 2025-10-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleado_area_empleado_tipo_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='hijo',
            options={'ordering': ['nombre'], 'verbose_name': 'Hijo', 'verbose_name_plural': 'Hijos'},
        ),
        migrations.AlterModelOptions(
            name='historialcargosalario',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Historial de Cargo y Salario', 'verbose_name_plural': 'Historiales de Cargos y Salarios'},
        ),
    ]
