# Generated by Django 5.2.6 on 2025-10-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_empleado_options_alter_hijo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hijo',
            options={},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='area',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_contrato',
        ),
    ]
