# Generated by Django 5.2.6 on 2025-10-02 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único para cada usuario (login preferido)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente_rrhh', 'Gerente RRHH'), ('asistente_rrhh', 'Asistente RRHH'), ('empleado', 'Empleado')], default='empleado', help_text='Rol asignado al usuario dentro del sistema', max_length=20),
        ),
    ]
