# Generated by Django 5.2.6 on 2025-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_created_at_usuario_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente_rrhh', 'Gerente RRHH'), ('asistente_rrhh', 'Asistente RRHH'), ('empleado', 'Empleado')], db_index=True, default='empleado', help_text='Rol asignado al usuario dentro del sistema', max_length=20),
        ),
    ]
