# Generated by Django 5.2.6 on 2025-10-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_rename_reside_py_hijo_residente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(default='manual', max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichadas', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('minutos_trabajados', models.IntegerField(default=0)),
                ('estado', models.CharField(default='presente', max_length=15)),
                ('justificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
