# Generated by Django 5.2.6 on 2025-10-26 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=64)),
                ('accion', models.CharField(choices=[('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE')], max_length=10)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'accion', 'fecha'], name='auditoria_a_modelo_fe5542_idx')],
            },
        ),
    ]
