# Generated by Django 5.2.6 on 2025-10-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditoria_a_modelo_fe5542_idx',
        ),
    ]
